on:
  workflow_dispatch

name: Build

jobs:
  prebuild-node:
    name: Upload Node Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Change package name
        run: npm i npe -g && npe name "@apify/better-sqlite3-prebuilds" && npe repository.url "git+https://github.com/apify/better-sqlite3-prebuilds.git"
      - name: Show package.json
        run: cat package.json
      - name: Build release
        run: npx prebuild -r node --all -u ${{ secrets.GITHUB_TOKEN }}
