on:
  workflow_dispatch

name: Prebuild

jobs:
  prebuild-node:
    name: Upload Node Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Change package name
        run: npm i npe -g && npe name "better-sqlite3-prebuilds" && npe repository.url "git+https://github.com/apify/better-sqlite3-prebuilds.git"
        continue-on-error: true # release might be already changed
      - name: Show package.json
        run: cat package.json
      - name: Create a release
        continue-on-error: true # release might already exist
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: build release
        run: npx prebuild -r node -t 10.20.0 -t 12.0.0 -t 14.0.0 -u ${{ secrets.GITHUB_TOKEN }}
