on:
  workflow_dispatch

name: Build

jobs:
  prebuild-node:
    name: Upload Node Prebuild
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npe globally
        run: npm i npe -g
        # Might not be needed anymore with a new version of the package
#      - name: Change ABI version
#        run: npe "devDependencies.node-abi" "2.18.0"
      - run: npm install && (npm list || true)
      - name: Change package name
        run: npe name "better-sqlite3-with-prebuilds" && npe repository.url "git+https://github.com/apify/better-sqlite3-with-prebuilds.git"
      - name: Show package.json
        run: cat package.json
      - name: Build release
        run: |
          node ./node_modules/prebuild/bin.js -r node -t 10.20.0 -t 12.0.0 -t 14.0.0 -t 15.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}
