on:
  workflow_dispatch

name: Publish

jobs:
  prebuild-node:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Change package name
        run: npm i npe -g && npe name "@apify/better-sqlite3-prebuilds" && npe repository.url "git+https://github.com/apify/better-sqlite3-prebuilds.git"
      - name: Prepare for installing lzz
        run: mkdir /tmp/lzz_arch && cd /tmp/lzz_arch && curl -sS https://github.com/driedfruit/lzz/releases/download/v2.8.2/lzz_2_8_2_linux64.zip > lzz.zip && unzip lzz.zip
      - name: DEBUG ZIP
        run: ls -la
      - name: Try LZZ
        run: /tmp/lzz_arch/lzz
      - uses: JS-DevTools/npm-publish@v1
        continue-on-error: true # release might be already done and the prepublish fails on windows
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: true
